/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export enum NestedBirdAgeUnit {
    Months = "months",
    Years = "years",
    Days = "days",
}

export class NestedBirdAge extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    unit: NestedBirdAgeUnit;
}

export class NestedBirdFlightWingsSpan extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "unit" })
    unit?: string;
}

export class NestedBirdFlightWings extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "count" })
    count?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "span" })
    @Type(() => NestedBirdFlightWingsSpan)
    span?: NestedBirdFlightWingsSpan;
}

export class NestedBirdFlight extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "canFly" })
    canFly?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "wings" })
    @Type(() => NestedBirdFlightWings)
    wings?: NestedBirdFlightWings;
}

export class NestedBirdLocationGeography extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "latitude" })
    latitude?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "longitutde" })
    longitutde?: string;
}

export class NestedBirdLocation extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "geography" })
    @Type(() => NestedBirdLocationGeography)
    geography?: NestedBirdLocationGeography;
}

export class NestedBird extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "age" })
    @Type(() => NestedBirdAge)
    age?: NestedBirdAge;

    @SpeakeasyMetadata()
    @Expose({ name: "flight" })
    @Type(() => NestedBirdFlight)
    flight?: NestedBirdFlight;

    @SpeakeasyMetadata()
    @Expose({ name: "food" })
    food?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata({ elemType: NestedBirdLocation })
    @Expose({ name: "location" })
    @Type(() => NestedBirdLocation)
    location?: NestedBirdLocation[];

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}
