/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

export class CreateAnimalSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=oauth2;name=Authorization" })
    key1: string;
}

export class CreateAnimalRequestBody extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "age" })
    age?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "color" })
    color: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;
}

export class CreateAnimalResponse extends SpeakeasyBase {
    /**
     * OK
     */
    @SpeakeasyMetadata()
    animals?: shared.Animals;

    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Internal Server Error
     */
    @SpeakeasyMetadata()
    error?: shared.ErrorT;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
