/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class CreateNewBird200ApplicationJSONMeta extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "pagination" })
    @Type(() => shared.Pagination)
    pagination?: shared.Pagination;

    @SpeakeasyMetadata()
    @Expose({ name: "traceId" })
    traceId?: string;
}

/**
 * OK
 */
export class CreateNewBird200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => shared.NestedBird)
    data?: shared.NestedBird;

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => CreateNewBird200ApplicationJSONMeta)
    meta?: CreateNewBird200ApplicationJSONMeta;
}

export class CreateNewBirdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    createNewBird200ApplicationJSONObject?: CreateNewBird200ApplicationJSON;
}
