/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetAllDataRequest extends SpeakeasyBase {
    /**
     * include all filters
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=filter" })
    filter?: any[];
}

export class GetAllData200ApplicationJson2MetaPagination extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "pageNumber" })
    pageNumber?: number;
}

export class GetAllData200ApplicationJson2Meta extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "pagination" })
    @Type(() => GetAllData200ApplicationJson2MetaPagination)
    pagination?: GetAllData200ApplicationJson2MetaPagination;
}

export class GetAllData200ApplicationJson2 extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: shared.Animals })
    @Expose({ name: "animals" })
    @Type(() => shared.Animals)
    animals?: shared.Animals[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => GetAllData200ApplicationJson2Meta)
    meta?: GetAllData200ApplicationJson2Meta;
}

export class GetAllData200ApplicationJson1MetaPagination extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "pageNumber" })
    pageNumber?: number;
}

export class GetAllData200ApplicationJson1Meta extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "pagination" })
    @Type(() => GetAllData200ApplicationJson1MetaPagination)
    pagination?: GetAllData200ApplicationJson1MetaPagination;
}

export class GetAllData200ApplicationJson1 extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: shared.Birds })
    @Expose({ name: "birds" })
    @Type(() => shared.Birds)
    birds?: shared.Birds[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => GetAllData200ApplicationJson1Meta)
    meta?: GetAllData200ApplicationJson1Meta;
}

export class GetAllDataResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    getAllData200ApplicationJSONObject?: any;
}
