/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export * from "./deleteanimalsid";
export * from "./getanimals";
export * from "./patchanimalsid";
export * from "./postanimals";
