/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export * from "./createanimal";
export * from "./deleteanimalsbyid";
export * from "./getallanimals";
export * from "./getallbirds";
export * from "./getalldata";
export * from "./updateanimalsbyid";
