/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export * from "./createanimal";
export * from "./createnewbird";
export * from "./deleteanimalsbyid";
export * from "./getallanimals";
export * from "./getalllivingthings";
export * from "./updateanimalsbyid";
